trigger: 
- master

pool:
  name: Default

variables:
  - group: azure-marketplace

stages:
  - stage: Build_and_test
    jobs:
      - job:
        steps:
          - task: TfxInstaller@3
            displayName: "Install tfx-cli"
            inputs:
              version: "v0.7.x"
          - task: Npm@1
            displayName: "Install NPM Packages"
            inputs:
              command: 'install'
              workingDir: 'coverityTask'
          - task: Npm@1
            displayName: "Transpile TypeScript files"
            inputs:
              command: 'custom'
              workingDir: 'coverityTask'
              customCommand: 'run build'
